---

- hosts: localhost
  connection: local
  name: download tidb binaries
  tags:
      - local
  vars:
      root_pwd: "{{ lookup('env','ROOT_PWD') }}"
      tidb_pwd: "{{ lookup('env','TIDB_PWD') }}"
  tasks:
      - debug:
          msg: "verifying ROOT_PWD environment variable is set"
        failed_when: root_pwd == ''
      - debug:
          msg: "verifying TIDB_PWD environment variable is set"
        failed_when: tidb_pwd == ''
      - file:
          path: "{{ playbook_dir }}/downloads"
          state: directory
          mode: 0755
      - get_url:
          dest: "{{ playbook_dir }}/downloads/tidb-latest-linux-amd64.tar.gz"
          url: https://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
          checksum: sha256:https://download.pingcap.org/tidb-latest-linux-amd64.sha256
- hosts: all
  name: create tidb user
  tags:
      - create_user
  vars:
      ansible_user: root
      ansible_password: "{{ lookup('env','ROOT_PWD') }}"
      tidb_password: "{{ lookup('env','TIDB_PWD') }}"
  tasks:
      - user:
          name: tidb
          state: present
          system: yes
          password: "{{ tidb_password | password_hash('sha512', 'mysecretsalt') }}"
          expires: -1
